version: "3.9"
services:
  users_database:
    image: postgres:13
    environment:
      POSTGRES_DB: "user_database"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    expose:
      - "5432"

  unities_database:
    image: postgres:13
    environment:
      POSTGRES_DB: "unity_database"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./unities/database/2022-09-26.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5433"

  unities_service:
    build: ./unities
    environment:
      DB_HOST: "unity_database"
      DB_PORT: "5433"
      DB_NAME: "unity_database"
      DB_USER: "admin"
      DB_PASS: "admin"
      PROD: "True"
    command: python server.py
    ports:
      - "9001:8090"
    depends_on:
      - unities_database

  users_service:
    build: ./users
    environment:
      KEYCLOAK_URL: "keycloak"
      KEYCLOAK_CLIENT_ID: "backend"
      KEYCLOAK_CLIENT_SECRET: "***"
      PROD: "True"
    command: python server.py
    ports:
      - "9002:8090"
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    environment:
      DB_VENDOR: "POSTGRES"
      DB_ADDR: "postgres"
      DB_DATABASE: "user_database"
      DB_USER: "admin"
      DB_SCHEMA: "public"
      DB_PASSWORD: "admin"
      KEYCLOAK_ADMIN: "unicheck"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - users_database
